### PR TITLE
Create responsive nav bar + buttons for switching between user & world.

### PR DESCRIPTION
**Pull request by bharathcs**
I tried a couple of versions for the desktop UI (sidebar, topbar etc), and nothing really seemed to fit.
With the header in place, having a sidebar / additional topbar looks weird. In the end I went for setting buttons that appear only when screen >= medium.

Lmk what you guys think about this style.

Also I decided to move the "create" button out of the nav bar because the best practice for nav bar is to have all things on the same conceptual level (create application opens a create modal to add a single application, while Your List / Explore are different views on collections of applications).

### CODE REVIEW

**Comment by bharathcs** [comment]
https://user-images.githubusercontent.com/7360964/190884252-51774afa-3951-42de-adb7-0655e069bb9c.mov

**Comment by bharathcs** [comment]
Latest version: (blue like siva suggested cuz it looks better now with the create button)

https://user-images.githubusercontent.com/7360964/190902862-1d47801e-b6fc-4322-9f90-031b4c953738.mov

**Comment by bharathcs** [comment]
Latest: 


https://user-images.githubusercontent.com/7360964/190903431-77ee4f42-1309-48e6-b1aa-9b1699a01ca6.mov

**Review by sivayogasubramanian — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
