### PR TITLE
Create placeholder API files.

### PR DESCRIPTION
**Pull request by bharathcs**
- Add placeholder API files
- Add placeholder API logic.

### CODE REVIEW

**Comment by zognin** [comment]
Thanks for setting up, siva tested the current endpoints and they work

- On hindsight siva and I think we don't need `/user/` before `/application/*` because it is unnecessary, shall we remove it?
  - If we decide to keep it then `/user/` can be changed to `/users/`
- Is `/companies` missing?

**Review by zognin — COMMENTED** [review]
Thanks for setting up, siva tested the current endpoints and they work

- On hindsight siva and I think we don't need `/user/` before `/applications/*` because it is unnecessary, shall we remove it?
  - If we decide to keep it then `/user/` can be changed to `/users/`
- Is `/companies` missing?

**Comment by bharathcs** [comment]
Sgtm, thanks for the catch too.

**Review by sivayogasubramanian — APPROVED** [review]
LGTM!

**Pull request merged**
